name: CI 

on : [push]
jobs:
    build-test:
       runs-on: ubuntu-latest
       steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Install Dependencies
              run: npm install
             
            - name: Cypress Tests
              uses: cypress-io/github-action@v6
                  
            - uses: actions/upload-artifact@v4
              if: always()
              with: 
                  name: Cypress Result
                  path: |
                      cypress/screenshots 
                      cypress/videos
                      cypress/results
                  if-no-files-found: ignore
