name: CI

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4         

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test

     
